<a href="https://colab.research.google.com/github/Iinayah/Tugas2_DataMining/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset = pd.read_csv('DataPenjualanBarang Toko Lidya.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [3]:
print(x)

[['GUNA' 1 1 1 1 0 0 1 0 1]
 ['MULYA' 1 1 1 0 0 0 0 0 0]
 ['SUDARMA' 0 0 1 1 1 1 1 0 1]
 ['YASA' 1 0 0 1 1 0 0 1 0]
 ['ZABDIEL' 0 1 0 0 1 1 1 1 1]
 ['DANIEL' 1 1 1 1 1 0 0 1 0]
 ['JUNIEL' 0 1 0 0 0 1 1 1 1]
 ['YUDA' 1 0 0 1 0 0 1 0 0]
 ['YUDIK' 1 1 1 0 1 1 0 1 0]
 ['PRADANA' 0 0 1 1 0 1 1 0 1]
 ['PUTRA' 1 1 0 1 1 0 0 1 1]
 ['DEWA' 0 0 0 1 0 1 1 0 0]
 ['GEDE' 0 0 1 0 1 1 0 1 0]
 ['BUDI' 1 1 0 0 0 0 1 0 0]
 ['ARYAWAN' 0 1 1 1 1 0 0 1 1]
 ['ADIT' 1 1 0 0 0 1 1 1 1]
 ['PURNOMO' 0 0 0 0 0 0 0 1 1]
 ['SURYA' 1 0 1 0 1 1 1 0 1]
 ['WIJAYA' 1 1 1 1 1 0 0 1 0]
 ['KUSUMA' 1 0 0 1 0 1 1 0 1]]


In [4]:
print(y)

[0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 1]


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [6]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 1 1 0 0 1 0 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 1 0 0 0 0 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0 0 1 1 1 1 1 0 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 1 0 0 1 1 0 0 1 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 0 1 0 0 1 1 1 1 1]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 1 1 1 0 0 1 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0 1 0 0 0 1 1 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 1 0 0 1 0 0 1 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 0.0 1 1 1 0 1 1 0 1 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
print(y)

[0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 1]


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [10]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0 0 1 1 1 1 1 0 1]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0 1 1 1 1 0 0 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 0 1 0 0 1 1 1 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 1 0 1 0 1 1 1 0 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 1 0 0 1 0 0 1 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 1 0 0 0 0 0 0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 0 0 0 0 1 0 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 1 1 0 0 1 0 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 0 0 1 0 1 1 0 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0

In [11]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 1 0 0 1 1 0 0 1 0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0 0 0 0 0 0 0 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 0 1 0 0 0 1 1 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 1 1 0 1 1 0 0 1 1]]


In [12]:
print(y_train)

[0 0 0 0 1 1 0 0 1 0 1 1 0 1 1 1]


In [13]:
print(y_test)

[1 1 0 0]


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [15]:
print(x_train)

[[0.0 0.0 0.0 -0.2581988897471611 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 0.0 3.8729833462074166 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 -1.2909944487358056 -1.1338934190276817
  0.7745966692414834 0.8819171036881969 1.0 0.8819171036881969
  0.7745966692414834 -0.8819171036881969 1.0]
 [0.0 1.0 0.0 -0.2581988897471611 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 -1.2909944487358056 0.8819171036881969
  0.7745966692414834 0.8819171036881969 1.0 -1.1338934190276817
  -1.2909944487358056 1.1338934190276817 1.0]
 [0.0 0.0 0.0 -0.2581988897471611 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581

In [16]:

print(x_test)

[[0.0 0.0 0.0 -0.2581988897471611 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 1.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.7745966692414834 -1.1338934190276817
  -1.2909944487358056 0.8819171036881969 1.0 -1.1338934190276817
  -1.2909944487358056 1.1338934190276817 -1.0]
 [0.0 0.0 0.0 -0.2581988897471611 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 1.0 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 0.0 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 -1.2909944487358056 -1.1338934190276817
  -1.2909944487358056 -1.1338934190276817 -1.0 -1.1338934190276817
  -1.2909944487358056 1.1338934190276817 1.0]
 [0.0 0.0 0.0 -0.2581988897471611 -0.2581988897471611 -0.2581988897471611
  -0.2581988897471611 1.0 